{
  tagline: "...",
  descripcion: "...",
  activo: true,
  telefono: "...",
  whatsapp: "...",
  email_contacto: "...",
  website: "...",
  direccion: "...",
  ciudad: "...",
  provincia: "...",
  google_maps_embed: "...",
  instagram: "...",
  facebook: "...",
  tiktok: "...",
  chatbot_webhook_url: "...",
  chatbot_api_token: "...",
  chatbot_api_base_url: "...",
  color_primario: "#355063",
  color_secundario: "#05254C",
  plantilla: "clasica",
  horarios: [{ dias: "...", hora: "..." }],
  servicios: [{ icono: "🦷", titulo: "...", descripcion: "..." }],
  fotos: ["url1", "url2", ...],
  testimonios: [{ nombre: "...", comentario: "...", reputacion: 5 }],
  updated: "2026-...",
  created_at: "..." // opcional
}
